ajou-exchangers/BE

app.js, controllers/authController.js, services/userService.js
=> Fix: 인증, 인가 이슈 수정

services/userService.js
=> chore: auth api 예외 처리 추가

controllers/locationController.js, routes/location.js, services/locationService.js
> 구현 사항 및 작업 내역
- 장소 이름에 대해 한글과 영어 검색 가능
- 카테고리 검색 가능
- 쿼리스트링으로 검색어 전달 (ex. /api/exchangers/v1/locations?search=농협&category=Bank)
<br/>
=> Feat 장소 검색 api 구현

constants/errorMessage.js, controllers/keywordController.js, controllers/reviewController.js, dto/review/UpdateReviewRequest.js, dto/review/WriteReivewRequest.js, models/Keyword.js, models/Review.js, routes/review.js, services/reviewService.js
=> Chore review

dto/LocationApplyRequest.js, dto/location/LocationReadResponse.js, package-lock.json, package.json, services/locationService.js, utils/ReviewAverage.js
> 구현 사항 및 작업 내역
main pull 받을 시 파파고 키 추가 필요
<br/>
=> Feat location

controllers/authController.js, dto/response/LoginResponse.js, routes/auth.js, services/userService.js
=> Chore: Auth API 수정

controllers/boardController.js, services/boardService.js
=> Fix: post 삭제 이슈 수정

constants/errorMessage.js, constants/responseMessage.js, controllers/reviewController.js, routes/review.js, services/reviewService.js
=> Chore review 로그인 연동 및 로직 수정

constants/errorMessage.js, services/reviewService.js
=> Fix 리뷰 수정 및 삭제 예외 처리 수정

services/locationService.js
=> Chore location  , 수정 신청 api 예외 처리 수정

controllers/boardController.js, routes/board.js, services/boardService.js
=> Feat: 좋아요 기능 추가

controllers/adminController.js, services/adminService.js
=> Chore : 등록 수락하지 않은 장소 목록 조회 시 페이징 처리

constants/errorMessage.js, models/Comment.js, models/Post.js, services/boardService.js, services/commentService.js, services/reviewService.js
=> Chore: board, comment 스키마에 updatedAt 추가, 에러 메시지 상수화하여 적용

constants/domains.js, constants/errorMessage.js, controllers/authController.js, services/authService.js, services/userService.js
=> Chore: 회원 인증 로직 수정

constants/errorMessage.js, constants/responseMessage.js, controllers/adminController.js, routes/admin.js, services/adminService.js
=> Feat admin

dto/location/LocationUpdateRequest.js, models/LocationUpate.js
=> Chore : 장소 수정 신청에 이유 필드 추가

dto/LocationApplyRequest.js, dto/location/LocationUpdateRequest.js, services/locationService.js
=> Chore : 장소 수정 및 등록 주소도 파파고 번역 적용

constants/errorMessage.js, middlewares/authMiddleware.js, services/authService.js, services/boardService.js, services/commentService.js, services/userService.js
=> Fix: auth 에러 메시지 적용

models/Location.js, services/locationService.js
=> chore : Location 캐시 컬럼 추가

controllers/reviewController.js, services/reviewService.js
=> Chore : 리뷰 crud 시 location 리뷰 총점, 평균, 개수 갱신하도록 수정

app.js, models/User.js
=> Chore: User 스키마에 emailVerified 필드 추가 및 적용

app.js
=> Chore: User emailVerified 필드 update문 삭제

controllers/authController.js
=> Fix: 닉네임 중복확인 로직 수정

app.js, constants/errorMessage.js, controllers/authController.js, middlewares/authMiddleware.js, package-lock.json, package.json, routes/auth.js, services/authService.js, services/emailService.js, services/userService.js, utils/cryptoUtils.js
=> Feat: 이메일 인증 구현

services/emailService.js, utils/cryptoUtils.js
=> Chore: 이메일 인증 로직 수정

utils/cryptoUtils.js
=> Fix: 이메일 인증을 위한 crypto 로직 수정

utils/cryptoUtils.js
=> Fix: crypto 로직 변경

services/reviewService.js
> 구현 사항 및 작업 내역
location의 review관련 캐시컬럼도 업데이트하기 때문에 데이터 일관성을 위해 트랜잭션 적용
<br/>
=> chore : review crud시 트랜잭션 적용

constants/errorCodes.js, constants/errorMessage.js, controllers/locationController.js, services/locationService.js, utils/LocationUtil.js
=> Chore : Location Api 코드 수정 및 예외 처리 추가

services/adminService.js
=> chore : location 등록 수락시 위도, 경도, 장소 이름이 같은 경우 추가시 예외 처리

services/locationService.js, utils/LocationUtil.js
> 구현 사항 및 작업 내역
위와 같이 구현한 이유는 파파고 api에서 아주대점을 the great point 이렇게 번역이 되어 아주대학교점이라고 변환한 후 번역
<br/>
=> chore : 장소 추가 수정 시 장소 이름에 아주대점 수원아주대점이 존재하면 아주대학교점으로 교체

services/locationService.js
=> fix : 아주대점 키워드가 존재하면 아주대학교점이라고 변경후 번역 카카오맵 장소이름은 그래도 저장하도록 변경

services/emailService.js, utils/cryptoUtils.js
=> Fix: 이메일 인증 로직 수정

dto/review/ReviewRequest.js
=> fix : 리뷰 작성 request dto 수정

constants/responseMessage.js, controllers/authController.js
=> Chore: Auth API에 ResponseMessage Constants 적용
